server:
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /v1/sys/health
    hosts:
      - host: vault.presentium.ch
        paths: []
  dataStorage:
    enabled: true
    storageClass: ebs
  auditStorage:
    enabled: true
    storageClass: ebs
  ui:
    enabled: true
  affinity: ""
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::123247571664:role/PRES-VAULT-KMS-PRESENTIUM
    name: vault
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      # language=hcl
      config: |
        ui = true
        cluster_name = "vault-presentium"
        storage "raft" {
          path    = "/vault/data/"
        }

        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable = "true"
        }
        service_registration "kubernetes" {}

        seal "awskms" {
          kms_key_id = "arn:aws:kms:eu-west-1:123247571664:alias/presentium/vault"
        }
